import 'package:flutter/material.dart';
const primarycolor=Color(0xffb51010);
const primarydarkcolor=Color(0xff254c54);
const textcolor=Color(0xffa8c0a0);
const green=Color(0xffb7c59b);
const greenlite=Color(0xffdfe8cf);
const white =Color(0xffffffff);
const offwhite=Color(0xffF1ECEC);
const gray =Color(0xffCECECE);
const grayTEXT=Color(0xff9F9D9B);
const appcolor=Color(0xffffd800);
const red =Color.fromRGBO(246, 20, 20, 1);
const orangelight =Color.fromRGBO(255, 162 , 0, 1);
const yellow =Color.fromRGBO(255, 193, 7, 1);
const orangedark = Color.fromRGBO(255, 85, 0, 1);
const blue =Color.fromRGBO(45, 95, 255, 1);
const kBlackColor =Color.fromRGBO(0, 0, 0, 1);
//*************************************************************************
const double fontLarge=27;
const double fontTitle=16;
const double fontSmall=13;
const double Dpadding=10;
const double fontsubtitle=14;
const double SizedBoxhieght=10;
const double RadiusCircular=30;